[package]
name = "rust-beginner"
version = "0.1.0"
authors = ["Mandip Tharu <mandip810@gmail.com>"]
edition = "2021"
cargo-features = ["edition2021"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.x"